# Generated by Django 4.0 on 2022-03-18 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('active_status', models.BooleanField(default=True)),
                ('floor_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('time_listed', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='tags', to='auctions.Category')),
                ('saver', models.ManyToManyField(related_name='watchlist', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_listings', to='auctions.user')),
            ],
            options={
                'ordering': ['time_listed'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time_commented', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_comments', to='auctions.user')),
            ],
            options={
                'ordering': ['time_commented'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('time_bid_placed', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.user')),
            ],
            options={
                'ordering': ['time_bid_placed'],
            },
        ),
    ]
